sudo: false # use newer travis infrastructure
language: ruby
rvm:
  - "2.1.8"
  - "2.2.4"
  - "2.3.0"
env:
  - "ACTIVERECORD_VERSION=4.2.6"
  - "ACTIVERECORD_VERSION=4.1.15"
  - "ACTIVERECORD_VERSION=4.0.13"
  - "ACTIVERECORD_VERSION=master"
matrix:
  allow_failures:
    # Master may or may not pass
    - env: "ACTIVERECORD_VERSION=master"
