version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2-node # use a tailored CircleCI docker image.
    steps:
      - checkout

      - run: bundle config set path 'vendor/bundle'
      - run: sudo apt-get update
      - run: sudo apt install libsqlite3-dev

      # There's probably a better way of doing this that avoids the repetition and manual
      # deletion of Gemfile.lock.
      - restore_cache:
          key: rails-5.2.4.4-{{ checksum "Gemfile" }}
      - run:
          name: bundle install
          command: bundle install
          environment:
            ACTIVERECORD_VERSION: 5.2.4.4
      - save_cache:
          key: rails-5.2.4.4-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Test with Rails 5.2
          command: bundle exec rspec

      - run: rm Gemfile.lock
      - restore_cache:
          key: rails-6.0.3.4-{{ checksum "Gemfile" }}
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
          environment:
            ACTIVERECORD_VERSION: 6.0.3.4
      - save_cache:
          key: rails-6.0.3.4-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - restore_cache:
          key: rails-6.0.3.4-{{ checksum "Gemfile" }}
      - run:
          name: Test with Rails 6.0
          command: bundle exec rspec
