version: 2.1

executors:
  ruby:
    docker:
      - image: cimg/ruby:3.2

jobs:
  test-rails:
    parameters:
      rails-version:
        type: string
    executor: ruby
    steps:
      - checkout
      - run: bundle config set path 'vendor/bundle'
      - run: sudo apt-get update
      - run: sudo apt install libsqlite3-dev
      - restore_cache:
          key: rails-<< parameters.rails-version >>-{{ checksum "Gemfile" }}
      - run:
          name: Bundle install
          command: bundle install
          environment:
            ACTIVERECORD_VERSION: << parameters.rails-version >>
      - save_cache:
          key: rails-<< parameters.rails-version >>-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Test with Rails << parameters.rails-version >>
          command: bundle exec rspec
          environment:
            ACTIVERECORD_VERSION: << parameters.rails-version >>

workflows:
  test-all-rails-versions:
    jobs:
      - test-rails:
          matrix:
            parameters:
              rails-version: ["7.0.8.7", "7.1.5.1", "8.0.2"]
