version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.2
    steps:
      - checkout

      # There's probably a better way of doing this that avoids the repetition and manual
      # deletion of Gemfile.lock.
      - restore_cache:
          key: rails-4.2.9-{{ checksum "Gemfile" }}
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
          environment:
            ACTIVERECORD_VERSION: 4.2.9
      - save_cache:
          key: rails-4.2.9-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Test with Rails 4.2.9
          command: bundle exec rspec

      - run: rm Gemfile.lock
      - restore_cache:
          key: rails-5.0.6-{{ checksum "Gemfile" }}
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
          environment:
            ACTIVERECORD_VERSION: 5.0.6
      - save_cache:
          key: rails-5.0.6-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - restore_cache:
          key: rails-5.0.6-{{ checksum "Gemfile" }}
      - run:
          name: Test with Rails 5.0.6
          command: bundle exec rspec

      - run: rm Gemfile.lock
      - restore_cache:
          key: rails-5.1.4-{{ checksum "Gemfile" }}
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
          environment:
            ACTIVERECORD_VERSION: 5.1.4
      - save_cache:
          key: rails-5.1.4-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Test with Rails 5.1.4
          command: bundle exec rspec
